# Generated by Django 5.1 on 2024-09-10 13:52

import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education')], max_length=50)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
