# Generated by Django 5.1 on 2024-09-11 12:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
