# Generated by Django 5.1 on 2024-09-11 17:20

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
