# Generated by Django 5.1 on 2024-09-12 07:29

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cloudinaryattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudinaryAttachment',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
