# Generated by Django 5.1 on 2024-09-12 09:32

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_cloudinaryattachment_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
