# Generated by Django 5.1 on 2024-10-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_comment_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('health', 'Health')], max_length=50),
        ),
    ]
