# Generated by Django 5.1 on 2024-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('business-finance', 'Business & Finance'), ('digital-marketing', 'Digital Marketing'), ('travel', 'Travel'), ('fashion-beauty', 'Fashion & Beauty'), ('health', 'Health & Wellness'), ('education-learning', 'Education & Learning'), ('art-entertainment', 'Art & entertainment'), ('science-nature', 'Science & Nature'), ('Personal-developmemnt', 'Personal Development'), ('home-lifestyle', 'Home & lifestyle'), ('news-politics', 'News & Politics'), ('food-drink', 'Food & Drink'), ('Hobbies-liesure', 'Hobbies & Leisure'), ('Sports', 'Sports'), ('parenting-family', 'Parenting & Family'), ('automative', 'Automative'), ('environment-sustainability', 'Environment & Sustainability'), ('gaming', 'Gaming'), ('spirituality-religion', 'Spirituality & Religion'), ('real-estate', 'Real Estate'), ('diy-crafts', 'DIY & Crafts'), ('animal-pets', 'Animal & Pets')], max_length=50),
        ),
    ]
